package dev.ivanlepi.twitchclips.service;

import dev.ivanlepi.twitchclips.models.Clip;
import dev.ivanlepi.twitchclips.models.Game;
import dev.ivanlepi.twitchclips.repository.GameRepository;
import dev.ivanlepi.twitchclips.repository.ClipsRepository;
import java.util.List;

public class GamelistService {

    private final GameRepository gameRepository;
	private final ClipsRepository clipRepository;

	public GamelistService(GameRepository gameRepository, ClipsRepository clipRepository) {
		this.gameRepository = gameRepository;
		this.clipRepository = clipRepository;
	}

	/**
	 * This method returns the list of games from our database.
	 */
	public List<Game> getGames(){
		return gameRepository.findAll();
	}
	
	/**
	 * This method returns the list of Clips for selected game.
	 * @param game_id Every game object has game_id parameter.
	 * @return List<Clip> This returns list of Clips generated by findByGameId() method.
	 */
    public List<Clip> getGameClips(String game_id) {
		//Pageable page = PageRequest.of(0, 10);
        return clipRepository.findBy(game_id, "");
    }


	/**
	 * This method returns the list of Clips for selected Broadcaster.
	 * @param broadcaster_id Every Clip has a field with broadcaster_id
	 * @return List<Clip> This returns list of Clips generated by findByBroadcasterId() method.
	 */
    public List<Clip> getBroadcasterClips(String broadcaster_id) {
		return clipRepository.findBy("",broadcaster_id);
    }

}
