version: "3.7"

services:
  api: 
    depends_on: 
      - mongo
    image: twitchclips:0.0.1-SNAPSHOT
    ports: 
      - 8080:8080
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  scheduler:
    depends_on: 
      - mongo
    image: devosdev/twitchscheduler:0.0.2-SNAPSHOT
    ports: 
      - 8082:8082
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    

  mongo:
    image: mongo
    restart: always
    volumes: 
      - twitchclips-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  twitchclips-db: